version: "3.5"

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ttmik
      - POSTGRES_USER=ttmik
      - POSTGRES_PASSWORD=ttmik
