info:
  app:
    name: service-ttmik
    version: 1.0.0-SNAPSHOT

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/ttmik # started in a Docker container, see docker-compose.yml
    username: ttmik
    password: ttmik
    continue-on-error: true
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      data-source-properties:
        socketTimeout: 120
  flyway:
    table: schema_version
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        globally_quoted_identifiers: true
